### ISSUE TITLE
Doesn't run on MacOS

### ISSUE THREAD

**Issue by r-moore** [rahulpsd18/cognito-backup-restore#23]
There is a bug in `src/cli/cli.ts` (line 1) that causes the following error on MacOS:
`env: node\r: No such file or directory`

I think the CRLF line ending is causing it, but perhaps the shebang line could be removed altogether as it is not widely used.

**Comment by rahulpsd18** [comment]
Can you please try using v1.3.1 and let me know if this is indeed fixed?

Please re-open if it is still an issue.

**Comment by jimmyn** [comment]
This is still an issue in the latest version. You need to fix line endings
