### ISSUE TITLE
Import the same sub ids

### ISSUE THREAD

**Issue by kyangy** [rahulpsd18/cognito-backup-restore#8]
After creating the backup, how can we import the same sub ids when we restore to a new pool? It generates new sub ids when you restore.

**Comment by rahulpsd18** [comment]
As per the response from AWS Employee on [this thread](https://forums.aws.amazon.com/message.jspa?messageID=766242#766242), **`sub` is globally unique and hence is unique for user pool as well. Unlike username, which can be reassigned to another user in user pool, sub is never reassigned.**

Hope this answers your question.
